import ItemBase from "./ItemBase";
import ItemBlossom from "./Items/ItemBlossom";
import ItemCrossCloud from "./Items/ItemCrossCloud";
import ItemFightWithBothHands from "./Items/ItemFightWithBothHands";
import ItemScatterAtkWarCore from "./Items/ItemScatterAtkWarCore";
import ItemWarCore from "./Items/ItemWarCore";
import ItemYijingRing from "./Items/ItemYijingRing";
import ItemGatheringStorm from "./Items/ItemGatheringStorm";
import ItemMoreScatter from "./Items/ItemMoreScatter";
import ItemFastScatter from "./Items/ItemFastScatter";
import ItemOrbitsAtkWarCore from "./Items/ItemOrbitsAtkWarCore";
import ItemAddKnife from "./Items/ItemAddKnife";
import ItemExtKnifeSize from "./Items/ItemExtKnifeSize";
import Item_WarCore_BaseWarCore from "./WarCore/Item_WarCore_BaseWarCore";
import Item_WarCore_ScatterWarCore from "./WarCore/Item_WarCore_ScatterWarCore";
import Item_WarCore_RhombusPunchWarCore from "./WarCore/Item_WarCore_RhombusPunchWarCore";
import Item_WarCore_SwordMasterWarCore from "./WarCore/Item_WarCore_SwordMasterWarCore";
import ItemBasic from "./ItemBasic";
import Item_UPack_Mirror from "./UpgradePack/Item_UPack_Mirror";
import Item_UPack_Fission from "./UpgradePack/Item_UPack_Fission";
import Item_UPack_Penetrate from "./UpgradePack/Item_UPack_Penetrate";
import Item_UPack_Readyfor from "./UpgradePack/Item_UPack_Readyfor";
import Item_UPack_Overload from "./UpgradePack/Item_UPack_Overload";
import Item_UPack_BreakPunch from "./UpgradePack/Item_UPack_BreakPunch";
import Item_UPack_FastShadow from "./UpgradePack/Item_UPack_FastShadow";
import Item_UPack_Besieged from "./UpgradePack/Item_UPack_Besieged";
import Item_UPack_MentalAura from "./UpgradePack/Item_UPack_MentalAura";

export namespace Item_def {
    // export const Item_Base = ItemBase;
    export const Item_Basic = ItemBasic;
    export const Item_YijingRing = ItemYijingRing;
    export const Item_WarCore = ItemWarCore;
    export const Item_Blossom = ItemBlossom;
    export const Item_WarCoreBaseWarCore = Item_WarCore_BaseWarCore;
    export const Item_WarCoreScatterWarCore = Item_WarCore_ScatterWarCore;
    export const Item_WarCoreRhombusPunchWarCore = Item_WarCore_RhombusPunchWarCore;
    export const Item_WarCoreSwordMasterWarCore = Item_WarCore_SwordMasterWarCore;
    export const Item_UPackMirror = Item_UPack_Mirror;
    export const Item_UPackFission = Item_UPack_Fission;
    export const Item_UPackPenetrate = Item_UPack_Penetrate;
    export const Item_UPackReadyfor = Item_UPack_Readyfor;
    export const Item_UPackOverload = Item_UPack_Overload;
    export const Item_UPackBreakPunch = Item_UPack_BreakPunch;
    export const Item_UPackFastShadow = Item_UPack_FastShadow;
    export const Item_UPackBesieged = Item_UPack_Besieged;
    export const Item_UPackMentalAura = Item_UPack_MentalAura;
}
